### ISSUE TITLE
Move hooks to root folder 

### ISSUE THREAD

**Issue by satvik-1203** [ds-visualizer/ds-visualizer#82]

**Comment by ManuelMaciel** [comment]
Can I take this @satvik-1203 ?

**Comment by satvik-1203** [comment]
Feel free

**Comment by satvik-1203** [comment]
By the way, How did u find this?

**Comment by ManuelMaciel** [comment]
I saw my project was visited from a website, goodfirstissues, I thought it was great and saw your issue

**Comment by satvik-1203** [comment]
Perfect, Ill accept the pr once I get free :). Great work

**Comment by ManuelMaciel** [comment]
Thank you so much! <3
